#!/usr/bin/env php
<?php

use \DgfipSI1\Application\Application;

$cwd = isset($_SERVER['PWD']) && is_dir($_SERVER['PWD']) ? $_SERVER['PWD'] : getcwd();
$loader = false;
if (file_exists($autoloadFile = __DIR__ . '/vendor/autoload.php')
    || file_exists($autoloadFile = __DIR__ . '/../autoload.php')
    || file_exists($autoloadFile = __DIR__ . '/../../autoload.php')
) {
    $loader = include_once($autoloadFile);
} else {
    throw new \Exception("Could not locate autoload.php. cwd is $cwd; __DIR__ is " . __DIR__);
}
$app = new Application($loader, $argv);
$app->setApplicationName("Hello World");
$app->setApplicationVersion("1.0");
$app->findSymfonyCommands('Commands');
$app->finalize();
$statusCode = $app->run(); 

exit($statusCode);
