#!/usr/bin/env php
<?php

use \DgfipSI1\Application\RoboApplication;
$classLoader = require __DIR__.'/vendor/autoload.php';
$app = new RoboApplication($classLoader, $argv);
$app->setName("Hello World");
$app->setVersion("1.0");
$app->setNameSpace('roboFiles');
$statusCode=$app->go();

exit($statusCode);
