#!/usr/bin/env php
<?php

use \DgfipSI1\Application\Application;
$classLoader = require __DIR__.'/vendor/autoload.php';
$app = new Application($classLoader, $argv);
$app->setName("Hello World");
$app->setVersion("1.0");
$app->findRoboCommands('roboFiles');
$statusCode=$app->go();

exit($statusCode);
