people:
  "JSmith" :
    title: Mr
    name: Smith
    first_name: John
  "JDoe" :
    title: Ms
    name: Doe
    first_name: Jane
options:
    user: JSmith
    array_opt: [ 'one', 'two' ]
    boolean_opt: true
    scalar_opt: 'a string'
commands:
    hello:
        options:
            formal: true
